export const ARCHITECTURE_VERSION = '9.7.0-x2-x7';
export const APP_PRODUCT_VERSION = '9.7.0';
export const DATA_SCHEMA_VERSION = 14; // Deliberately unchanged: preserve all existing v8/v9 user data without destructive migration.
export const LEGACY_STORAGE_KEY = 'deutschweg_user_data';
export const LEGACY_CLOUD_SESSION_KEY = 'deutschWegFA_cloud_session';
export const LEGACY_KEYS = ['deutschWegFA_v6','deutschWegFA_v5','deutschWegFA_v4','deutschAdaptivePlanner_v3','deutschC1Planner_v2'];
export const IDB_NAME = 'deutschweg_x';
export const IDB_VERSION = 3;
export const FOUNDATION_MARKER = `architecture_backup_${ARCHITECTURE_VERSION}`;
export const RESOURCE_HEALTH_PATH = './resource-health.json';
export const RESOURCES_PATH = './resources.json';
